version: "3.8"

services:
  go:
    container_name: grass-go
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: go run cmd/main.go
    tty: true
    ports:
      - 8080:8080
    env_file:
      - ./mysql/.env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - type: bind
        source: ./backend/app
        target: /go/src

  db:
    container_name: grass-db
    build:
      context: ./mysql
      dockerfile: Dockerfile
    tty: true
    platform: linux/x86_64
    ports:
      - 3306:3306
    env_file:
      - ./mysql/.env
    volumes:
      - type: volume
        source: mysql_volume
        target: /var/lib/mysql
      - type: bind
        source: ./mysql/initdb.d
        target: /docker-entrypoint-initdb.d
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD
volumes:
  mysql_volume:
    name: grass-volume
